#!/usr/bin/env python3
# ============================================================
# update-palette.py — генерація палітри та тем зі шпалер
# ============================================================
# Генерує Palette.js, kitty тему, fish кольори, starship та yazi тему
# на основі поточних шпалер через matugen

import sys, json, subprocess, re, os

wallpaper = sys.argv[1]

result = subprocess.run(
    ["matugen", "image", wallpaper, "--source-color-index", "0", "--mode", "dark", "-j", "hex"],
    capture_output=True, text=True, check=True
)

data = json.loads(result.stdout)
raw = data["colors"]
palettes = data["palettes"]

# Отримує колір з raw
def col(name):
    return raw[name]["dark"]["color"]

# Отримує тон з палітри (neutral, primary, secondary, tertiary)
def tone(palette_name, level):
    return palettes[palette_name][str(level)]["color"]

def parse_hex(h):
    h = h.lstrip("#")
    if len(h) == 8: h = h[2:]
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)

def to_hex(r, g, b):
    return f"#{r:02x}{g:02x}{b:02x}"

# Змішує два кольори з коефіцієнтом t (0-1)
def blend(a, b, t):
    ra, ga, ba = parse_hex(a)
    rb, gb, bb = parse_hex(b)
    r = round(ra + (rb - ra) * t)
    g = round(ga + (gb - ga) * t)
    b = round(ba + (bb - ba) * t)
    return to_hex(r, g, b)

# Додає альфа-канал до кольору
def alpha(h, a):
    r, g, b = parse_hex(h)
    aa = round(max(0, min(1, a)) * 255)
    return f"#{aa:02x}{r:02x}{g:02x}{b:02x}"

fg        = col("on_background")
gray      = col("outline")
green     = tone("primary", 70)
red       = tone("error", 80)
bg0H      = tone("neutral", 20)
bg1       = tone("neutral", 25)
bg2       = tone("neutral", 35)
muted     = col("on_surface_variant")
light     = tone("neutral", 90)
bright    = tone("neutral", 95)
yellow    = col("tertiary")
blue      = col("secondary")
purple    = tone("secondary", 70)
orange    = tone("primary", 70)
aqua      = tone("tertiary", 70)

widgetFg   = blend(col("primary"), col("on_background"), 0.6)
audioVolume = tone("tertiary", 80)
accent     = col("primary")
textLight  = tone("neutral", 95)
mutedAlt   = blend(col("outline"), col("on_background"), 0.3)
danger     = col("error")
bgLayer    = alpha(blend(col("background"), col("on_surface"), 0.15), 0.6)
sepBg      = alpha(col("primary"), 0.6)
outlineVariant = alpha(bg2, 0.4)

# --- Palette.js ---

pal = f""".pragma library

var font = "JetBrainsMonoNL Nerd Font";

var fg       = "{fg}";
var gray     = "{gray}";
var green    = "{green}";
var red      = "{red}";

var bg0H     = "{bg0H}";
var bg1      = "{bg1}";
var bg2      = "{bg2}";
var muted    = "{muted}";
var light    = "{light}";
var bright   = "{bright}";

var yellow   = "{yellow}";
var blue     = "{blue}";
var purple   = "{purple}";
var orange   = "{orange}";
var aqua     = "{aqua}";

var widgetFg = "{widgetFg}";
var audioVolume = "{audioVolume}";

var hoverOverlay = "{alpha('#ffffff', 0.08)}";
var pressOverlay = "{alpha('#ffffff', 0.12)}";

var bgAlpha  = "{alpha(bg0H, 0.6)}";
var hoverBg  = "{alpha(blend(bg0H, gray, 0.15), 0.6)}";
var baseOverlay = "{alpha(bg0H, 0.6)}";
var softOverlay = "{alpha(bg0H, 0.65)}";

var accent   = "{accent}";
var textLight = "{textLight}";
var mutedAlt = "{mutedAlt}";
var danger   = "{danger}";
var bgLayer  = "{bgLayer}";
var sepBg    = "{sepBg}";
var outlineVariant = "{outlineVariant}";
"""

qs_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
with open(os.path.join(qs_dir, "Palette.js"), "w") as f:
    f.write(pal)

# --- kitty current-theme.conf ---

kitty_bg = tone("neutral", 20)

kitty = f"""## Generated by update-palette.py

selection_foreground    {fg}
selection_background    {blend(bg0H, accent, 0.35)}

background              {kitty_bg}
foreground              {fg}

color0                  {bg1}
color1                  {red}
color2                  {green}
color3                  {yellow}
color4                  {blue}
color5                  {purple}
color6                  {aqua}
color7                  {light}
color8                  {muted}
color9                  {blend(red, bright, 0.5)}
color10                 {blend(green, bright, 0.5)}
color11                 {orange}
color12                 {blend(blue, bright, 0.5)}
color13                 {blend(purple, bright, 0.5)}
color14                 {blend(aqua, bright, 0.5)}
color15                 {bright}

cursor                  {fg}
cursor_text_color       {bg0H}

url_color               {blue}

active_tab_foreground   {fg}
active_tab_background   {blend(bg0H, accent, 0.5)}
inactive_tab_foreground {muted}
inactive_tab_background {bg0H}
"""

kitty_path = os.path.expanduser("~/.config/kitty/current-theme.conf")
os.makedirs(os.path.dirname(kitty_path), exist_ok=True)
with open(kitty_path, "w") as f:
    f.write(kitty)

# --- fish conf.d/99-palette.fish ---

fish = f"""# Generated by update-palette.py
set -g fish_color_normal "{fg}"
set -g fish_color_command "{green}"
set -g fish_color_quote "{yellow}"
set -g fish_color_redirection "{purple}"
set -g fish_color_end "{purple}"
set -g fish_color_error "{red}"
set -g fish_color_param "{fg}"
set -g fish_color_comment "{muted}"
set -g fish_color_match --background={bg2.strip("#")}
set -g fish_color_selection --background={bg2.strip("#")}
set -g fish_color_search_match --background={bg2.strip("#")}
set -g fish_color_operator "{purple}"
set -g fish_color_escape "{aqua}"
set -g fish_color_autosuggestion "{muted}"
set -g fish_color_cwd "{blue}"
set -g fish_color_user "{green}"
set -g fish_color_host "{gray}"
set -g fish_color_status "{red}"
set -g fish_color_valid_path --underline
"""

fish_dir = os.path.expanduser("~/.config/fish/conf.d")
os.makedirs(fish_dir, exist_ok=True)
with open(os.path.join(fish_dir, "99-palette.fish"), "w") as f:
    f.write(fish)

# --- starship config.toml palette ---

starship_path = os.path.expanduser("~/.config/starship/config.toml")
if os.path.isfile(starship_path):
    with open(starship_path, "r") as f:
        content = f.read()

    palette_map = {
        "background":     bg0H,
        "current_line":   bg2,
        "foreground":     fg,
        "comment":        muted,
        "cyan":           aqua,
        "green":          green,
        "orange":         orange,
        "pink":           blend(red, bright, 0.6),
        "purple":         purple,
        "red":            red,
        "yellow":         yellow,
        "white":          bright,
    }

    lines = content.split("\n")
    in_palette = False
    new_lines = []
    for line in lines:
        stripped = line.strip()
        if stripped == "[palettes.tokyonight]":
            in_palette = True
            new_lines.append(line)
        elif in_palette and stripped.startswith("["):
            in_palette = False
            new_lines.append(line)
        elif in_palette:
            match = re.match(r'^(\s*)(\w+)\s*=\s*"(#[^"]*)"', line)
            if match:
                indent = match.group(1)
                key = match.group(2)
                if key in palette_map:
                    new_lines.append(f'{indent}{key} = "{palette_map[key]}"')
                else:
                    new_lines.append(line)
            else:
                new_lines.append(line)
        else:
            new_lines.append(line)

    with open(starship_path, "w") as f:
        f.write("\n".join(new_lines))

# --- yazi flavor ---

yazi_flavor_dir = os.path.expanduser("~/.config/yazi/flavors/palette.yazi")
os.makedirs(yazi_flavor_dir, exist_ok=True)

yazi_flavor = f"""# Generated by update-palette.py

[mgr]
cwd = {{ fg = "{green}" }}

find_keyword  = {{ fg = "{yellow}", bold = true, italic = true, underline = true }}
find_position = {{ fg = "{purple}", bg = "reset", bold = true, italic = true }}

marker_copied   = {{ fg = "{green}", bg = "{green}" }}
marker_cut      = {{ fg = "{red}", bg = "{red}" }}
marker_marked   = {{ fg = "{green}", bg = "{green}" }}
marker_selected = {{ fg = "{yellow}", bg = "{yellow}" }}

count_copied   = {{ fg = "{bg0H}", bg = "{green}" }}
count_cut      = {{ fg = "{bg0H}", bg = "{red}" }}
count_selected = {{ fg = "{bg0H}", bg = "{yellow}" }}

border_symbol = "│"
border_style  = {{ fg = "{bg2}" }}

[tabs]
active   = {{ fg = "{bg0H}", bg = "{green}", bold = true }}
inactive = {{ fg = "{green}", bg = "{bg1}" }}

[mode]
normal_main = {{ fg = "{bg1}", bg = "{green}", bold = true }}
normal_alt  = {{ fg = "{green}", bg = "{bg2}", bold = true }}

select_main = {{ fg = "{bg1}", bg = "{red}", bold = true }}
select_alt  = {{ fg = "{green}", bg = "{bg2}", bold = true }}

unset_main = {{ fg = "{bg1}", bg = "{green}", bold = true }}
unset_alt  = {{ fg = "{green}", bg = "{bg2}", bold = true }}

[status]
perm_sep   = {{ fg = "{bg0H}" }}
perm_type  = {{ fg = "{green}" }}
perm_read  = {{ fg = "{yellow}" }}
perm_write = {{ fg = "{red}" }}
perm_exec  = {{ fg = "{green}" }}

progress_label  = {{ bold = true }}
progress_normal = {{ fg = "{green}", bg = "{bg0H}" }}
progress_error  = {{ fg = "{red}", bg = "{bg0H}" }}

[pick]
border   = {{ fg = "{green}" }}
active   = {{ fg = "{purple}", bold = true }}
inactive = {{}}

[input]
border   = {{ fg = "{green}" }}
title    = {{}}
value    = {{}}
selected = {{ reversed = true }}

[cmp]
border   = {{ fg = "{green}" }}

[tasks]
border  = {{ fg = "{green}" }}
title   = {{}}
hovered = {{ fg = "{purple}", underline = true }}

[which]
mask            = {{ bg = "{bg0H}" }}
cand            = {{ fg = "{green}" }}
rest            = {{ fg = "{bg0H}" }}
desc            = {{ fg = "{purple}" }}
separator       = "  "
separator_style = {{ fg = "{bg0H}" }}

[help]
on      = {{ fg = "{green}" }}
run     = {{ fg = "{purple}" }}
hovered = {{ reversed = true, bold = true }}
footer  = {{ fg = "{bg0H}", bg = "{light}" }}

[spot]
border   = {{ fg = "{green}" }}
title    = {{ fg = "{green}" }}
tbl_col  = {{ fg = "{green}" }}
tbl_cell = {{ fg = "{yellow}", reversed = true }}

[notify]
title_info  = {{ fg = "{green}" }}
title_warn  = {{ fg = "{yellow}" }}
title_error = {{ fg = "{red}" }}

[filetype]
rules = [
\t{{ mime = "image/*", fg = "{purple}" }},
\t{{ mime = "{{audio,video}}/*", fg = "{purple}" }},
\t{{ mime = "application/{{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}}", fg = "{yellow}" }},
\t{{ mime = "application/{{pdf,doc,rtf}}", fg = "{blue}" }},
\t{{ mime = "vfs/{{absent,stale}}", fg = "{muted}" }},
\t{{ url = "*", fg = "{green}" }},
\t{{ url = "*/", fg = "{green}" }},
]
"""

with open(os.path.join(yazi_flavor_dir, "flavor.toml"), "w") as f:
    f.write(yazi_flavor)

# --- yazi theme.toml ---

yazi_theme = f"""# Generated by update-palette.py

[flavor]
dark = "palette"

[icon]
prepend_dirs = [
    {{ name = "Desktop",   text = "󰟀", fg = "{purple}" }},
    {{ name = "Documents", text = "󰈙", fg = "{green}" }},
    {{ name = "Downloads", text = "󰇚", fg = "{yellow}" }},
    {{ name = "Music",     text = "󰎆", fg = "{purple}" }},
    {{ name = "Pictures",  text = "󰉏", fg = "{blue}" }},
    {{ name = "Videos",    text = "󰕧", fg = "{orange}" }},
    {{ name = "Public",    text = "󰷌", fg = "{green}" }},
    {{ name = "Templates", text = "󰈔", fg = "{gray}" }},
]

prepend_conds = [
    {{ if = "dir", text = "󰉋", fg = "{green}" }},
]
"""

yazi_theme_path = os.path.expanduser("~/.config/yazi/theme.toml")
with open(yazi_theme_path, "w") as f:
    f.write(yazi_theme)
