## Згенеровано update-palette.py

    selection_foreground    #e8e8eb
    selection_background    #424a4f

    background              #121212
    foreground              #e8e8eb

    color0                  #1e1e1e
    color1                  #b5a3a3
    color2                  #9ab3c0
    color3                  #c8c8c8
    color4                  #b0b0b0
    color5                  #b0b0b0
    color6                  #9ab3c0
    color7                  #d0d0d0
    color8                  #9a9a9a
    color9                  #d5cccc
    color10                 #c8d4da
    color11                 #a8a8a8
    color12                 #d2d2d2
    color13                 #d2d2d2
    color14                 #c8d4da
    color15                 #f5f5f5

    cursor                  #e8e8eb
    cursor_text_color       #121212

    url_color               #b0b0b0

    active_tab_foreground   #e8e8eb
    active_tab_background   #566269
    inactive_tab_foreground #9a9a9a
    inactive_tab_background #121212
    