# ============================================================
# kitty/kitty.conf — конфігурація термінала Kitty
# ============================================================
shell fish

map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard
confirm_os_window_close 0
# ПОЧАТОК_ТЕМИ_KITTY — маркер для генератора теми
# Gruvbox Dark
include current-theme.conf
# КІНЕЦЬ_ТЕМИ_KITTY