# ============================================================
# starship/config.toml — конфігурація промпта Starship
# ============================================================
add_newline = false

palette = "self"

format = "$username$hostname$directory$git_branch$git_status$nodejs$python$rust$golang$cmd_duration$fill$time\n$character"

[palettes.self]
background = "#121212"
current_line = "#2c2c2e"
foreground = "#e8e8eb"
comment = "#9a9a9a"
cyan = "#9ab3c0"
green = "#9ab3c0"
orange = "#a8a8a8"
pink = "#dbd4d4"
purple = "#b0b0b0"
red = "#b5a3a3"
yellow = "#c8c8c8"
white = "#f5f5f5"
blue = "#b0b0b0"


[character]
success_symbol = "[ ](bold green) "
error_symbol = "[ ](bold red) "
vicmd_symbol = "[](bold purple) "

[fill]
symbol = " "

[username]
show_always = true
style_user = "bold white"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "comment"
format = "@[$hostname]($style) "

[container]
symbol = ' '
style = 'bold red dimmed'
format = '[$symbol \[$name\] ]($style)'

[os]
disabled = false
style = "bold white"

[os.symbols]
Ubuntu = " "
Debian = "󰣚 "
Fedora = " "
Pop = " "
Kali = " "
CachyOS = " 󰌽 "
Arch = " 󰣇"

#[custom.saludo]
#command = "echo Hi, $USER"
#when = "init"
#style = "bold green"
#format = " [$output]($style) "


[directory]
style = "bold cyan"

[git_branch]
symbol = " "
style = "comment"

[git_status]
style = "comment"

[nodejs]
symbol = " "
style = "comment"

[python]
symbol = " "
style = "comment"

[bun]
symbol = " "
style = "comment" 

[golang]
symbol = " "
style = "comment"

[time]
disabled = false
time_format = "%H:%M"
style = "comment"
format = "[$time]($style)"