[general]
bars = 28
framerate = 30
autosens = 1
sensitivity = 100

[input]
method = pulse
source = auto

[output]
method = raw
channels = mono
data_format = ascii
ascii_max = 1000

[smoothing]
monstercat = 1
noise_reduction = 0.4
