#!/usr/bin/env python3

import dbus
import dbus.service
import dbus.mainloop.glib
from gi.repository import GLib

BLUEZ = 'org.bluez'
AGENT_PATH = '/org/bluez/agent/qs_bt'
CAPABILITY = 'NoInputNoOutput'


class Agent(dbus.service.Object):
    @dbus.service.method('org.bluez.Agent1', in_signature='', out_signature='')
    def Release(self):
        pass

    @dbus.service.method('org.bluez.Agent1', in_signature='o', out_signature='s')
    def RequestPinCode(self, device):
        return '0000'

    @dbus.service.method('org.bluez.Agent1', in_signature='o', out_signature='u')
    def RequestPasskey(self, device):
        return dbus.UInt32(0)

    @dbus.service.method('org.bluez.Agent1', in_signature='ou', out_signature='')
    def DisplayPasskey(self, device, passkey):
        pass

    @dbus.service.method('org.bluez.Agent1', in_signature='ou', out_signature='')
    def DisplayPinCode(self, device, pincode):
        pass

    @dbus.service.method('org.bluez.Agent1', in_signature='o', out_signature='')
    def RequestConfirmation(self, device):
        return

    @dbus.service.method('org.bluez.Agent1', in_signature='o', out_signature='')
    def RequestAuthorization(self, device):
        return

    @dbus.service.method('org.bluez.Agent1', in_signature='os', out_signature='')
    def AuthorizeService(self, device, uuid):
        return

    @dbus.service.method('org.bluez.Agent1', in_signature='', out_signature='')
    def Cancel(self):
        pass


def main():
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
    bus = dbus.SystemBus()

    mgr = dbus.Interface(
        bus.get_object(BLUEZ, '/org/bluez'),
        'org.bluez.AgentManager1')

    try:
        mgr.UnregisterAgent(AGENT_PATH)
    except dbus.DBusException:
        pass

    agent = Agent(bus, AGENT_PATH)
    mgr.RegisterAgent(AGENT_PATH, CAPABILITY)
    mgr.RequestDefaultAgent(AGENT_PATH)

    try:
        GLib.MainLoop().run()
    except KeyboardInterrupt:
        pass


if __name__ == '__main__':
    main()
