# ============================================================
# hypridle.conf — бездіяльність: блокування та сон
# ============================================================
general {
    lock_cmd = pidof hyprlock || hyprlock                                     # уникнення запуску кількох інстансів hyprlock
    before_sleep_cmd = loginctl lock-session                                  # блокування перед сном
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # щоб не натискати клавішу двічі для ввімкнення дисплея
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 3600
    on-timeout = systemctl suspend
}